export interface EmojiOption {
  emoji: string;
  label: string;
  category: string;
  keywords: string;
}

type EmojiSeed = [emoji: string, label: string, keywords: string];

const EMOJI_GROUPS: Array<{ category: string; items: EmojiSeed[] }> = [
  {
    category: "Money",
    items: [
      ["💰", "Cash", "money cash savings finance"],
      ["💵", "Cash bill", "money dollars cash notes"],
      ["💴", "Yen cash", "money cash currency"],
      ["💶", "Euro cash", "money cash currency"],
      ["💷", "Pound cash", "money cash currency"],
      ["💳", "Payment card", "card credit debit payment finance"],
      ["🪙", "Coins", "coins cash savings finance"],
      ["🏦", "Bank", "bank finance savings"],
      ["🏧", "ATM", "atm cash withdrawal bank"],
      ["📈", "Investments", "investment stocks growth finance"],
      ["📉", "Losses", "stocks market down finance"],
      ["💹", "Market", "chart market stocks finance"],
      ["🧾", "Receipt", "receipt bills invoice expense"],
      ["🧮", "Calculator", "calculator budget math finance"],
      ["🔐", "Insurance", "security insurance protection"],
      ["💼", "Business", "business briefcase work income"],
      ["🧑‍💼", "Office worker", "salary work business job"],
      ["🎯", "Goal", "saving target budget goal"],
      ["⭐", "Priority", "favorite important priority"],
      ["🗂️", "Folder", "folder category files default"],
    ],
  },
  {
    category: "Food",
    items: [
      ["🛒", "Groceries", "groceries grocery shopping cart market supermarket"],
      ["🥦", "Vegetables", "vegetables produce healthy food groceries"],
      ["🥬", "Greens", "vegetables salad produce groceries"],
      ["🥕", "Carrots", "vegetables produce groceries"],
      ["🍎", "Fruit", "fruit apple produce groceries food"],
      ["🍌", "Bananas", "fruit banana produce groceries"],
      ["🍇", "Grapes", "fruit produce groceries"],
      ["🍓", "Berries", "fruit strawberry produce groceries"],
      ["🥩", "Meat", "meat protein butcher groceries food"],
      ["🍗", "Chicken", "chicken meat groceries food"],
      ["🐟", "Fish", "seafood fish groceries food"],
      ["🥚", "Eggs", "eggs breakfast groceries food"],
      ["🥛", "Milk", "milk dairy groceries food"],
      ["🧀", "Cheese", "cheese dairy groceries food"],
      ["🍞", "Bread", "bread bakery groceries food"],
      ["🥐", "Bakery", "croissant bakery breakfast"],
      ["🍚", "Rice", "rice grains groceries food"],
      ["🍝", "Pasta", "pasta noodles groceries food"],
      ["🍔", "Burger", "burger fast food restaurant"],
      ["🍕", "Pizza", "pizza food delivery restaurant"],
      ["🌮", "Tacos", "taco food restaurant"],
      ["🍜", "Noodles", "noodles ramen takeout restaurant"],
      ["🍣", "Sushi", "sushi dining restaurant"],
      ["🥗", "Salad", "salad healthy restaurant"],
      ["🍰", "Dessert", "cake dessert sweets"],
      ["🍦", "Ice cream", "ice cream dessert sweets"],
      ["☕", "Coffee", "coffee cafe tea drink"],
      ["🧋", "Bubble tea", "tea drink cafe"],
      ["🥤", "Drinks", "soda drink beverage"],
      ["🍿", "Snacks", "snacks cinema entertainment food"],
    ],
  },
  {
    category: "Home",
    items: [
      ["🏠", "Home", "home house rent mortgage"],
      ["🏡", "House", "home house garden"],
      ["🏢", "Office", "office work rent business"],
      ["🏘️", "Property", "property neighborhood rent"],
      ["🛋️", "Furniture", "furniture sofa home decor"],
      ["🛏️", "Bedroom", "bed bedroom home furniture"],
      ["🚪", "Door", "door home repair"],
      ["🪟", "Window", "window home repair"],
      ["🚿", "Bathroom", "shower bathroom plumbing"],
      ["🚽", "Toilet", "bathroom plumbing home"],
      ["🧻", "Paper", "toilet paper household"],
      ["🧹", "Cleaning", "cleaning home chores supplies"],
      ["🧽", "Sponge", "cleaning sponge supplies"],
      ["🧴", "Toiletries", "toiletries shampoo soap personal care"],
      ["🧼", "Soap", "soap cleaning toiletries"],
      ["🧺", "Laundry", "laundry washing clothes"],
      ["🪣", "Bucket", "cleaning bucket chores"],
      ["🔧", "Repairs", "repair maintenance tools fix"],
      ["🪛", "Tools", "screwdriver tools repair"],
      ["🔨", "Hammer", "tools repair maintenance"],
      ["🪜", "Ladder", "home repair ladder"],
      ["🪴", "Plants", "plants garden home decor"],
      ["🌱", "Garden", "garden plants home"],
      ["📦", "Packages", "packages delivery shipping online shopping"],
      ["🧯", "Safety", "safety extinguisher home"],
    ],
  },
  {
    category: "Bills",
    items: [
      ["💡", "Electricity", "electric electricity light utilities bills"],
      ["🔌", "Power", "power electricity plug utilities"],
      ["💧", "Water", "water utilities bill"],
      ["🔥", "Gas", "gas heating utilities bill"],
      ["🌐", "Internet", "internet wifi broadband utilities bill"],
      ["📶", "Wi-Fi", "wifi internet signal broadband"],
      ["📺", "TV", "tv cable subscription streaming"],
      ["📞", "Phone bill", "phone landline bill"],
      ["🛰️", "Satellite", "satellite cable internet"],
      ["🧊", "Cooling", "fridge cooling appliance utility"],
      ["❄️", "AC", "air conditioning cooling utility"],
      ["♨️", "Heating", "heating hot utility"],
      ["🧯", "Safety service", "safety service maintenance"],
      ["🪪", "License", "license document fee"],
      ["📄", "Documents", "paper documents fees"],
      ["📬", "Mail", "mail post bills"],
    ],
  },
  {
    category: "Transport",
    items: [
      ["⛽", "Fuel", "fuel petrol gas car transport"],
      ["🚗", "Car", "car vehicle auto transport"],
      ["🚙", "SUV", "suv car transport"],
      ["🚕", "Taxi", "taxi ride cab uber transport"],
      ["🚌", "Bus", "bus public transport commute"],
      ["🚆", "Train", "train rail public transport travel"],
      ["🚇", "Metro", "subway metro public transport"],
      ["🚲", "Bicycle", "bike bicycle transport"],
      ["🏍️", "Motorbike", "bike motorcycle transport delivery"],
      ["🛵", "Scooter", "scooter transport delivery"],
      ["🛺", "Rickshaw", "rickshaw transport"],
      ["🚚", "Truck", "truck moving delivery transport"],
      ["🅿️", "Parking", "parking car fee"],
      ["🛞", "Tires", "tire car maintenance"],
      ["🔋", "Charging", "battery ev charging car"],
      ["🧰", "Car repair", "mechanic repair car tools"],
      ["🚦", "Tolls", "traffic tolls commute"],
      ["🛣️", "Road trip", "road highway travel"],
    ],
  },
  {
    category: "Travel",
    items: [
      ["✈️", "Flight", "flight plane travel vacation"],
      ["🛫", "Departure", "flight departure travel"],
      ["🛬", "Arrival", "flight arrival travel"],
      ["🏨", "Hotel", "hotel stay travel vacation"],
      ["🧳", "Luggage", "luggage trip travel"],
      ["🗺️", "Map", "map travel trip"],
      ["🏖️", "Beach", "beach vacation travel"],
      ["🏔️", "Mountains", "mountain hiking vacation"],
      ["⛺", "Camping", "camping travel outdoors"],
      ["🎡", "Attractions", "theme park attractions travel"],
      ["🛂", "Passport", "passport immigration travel"],
      ["🛃", "Customs", "customs travel"],
      ["🗽", "Landmark", "landmark travel tourism"],
      ["🕌", "Mosque", "religious travel mosque"],
      ["🛕", "Temple", "temple religious travel"],
      ["⛩️", "Shrine", "shrine travel"],
      ["🚢", "Cruise", "ship cruise travel"],
      ["⛴️", "Ferry", "ferry boat travel"],
    ],
  },
  {
    category: "Health",
    items: [
      ["💊", "Medicine", "medicine pharmacy health medical"],
      ["🩺", "Doctor", "doctor clinic health medical"],
      ["🏥", "Hospital", "hospital health medical"],
      ["🚑", "Ambulance", "ambulance emergency medical"],
      ["🦷", "Dentist", "dentist dental health medical"],
      ["👓", "Glasses", "glasses eyewear health vision"],
      ["🧪", "Lab tests", "lab test medical health"],
      ["🩻", "X-ray", "xray scan medical"],
      ["🩹", "Bandage", "first aid medical"],
      ["🩼", "Recovery", "crutch recovery medical"],
      ["🧴", "Personal care", "lotion skincare personal care"],
      ["🏋️", "Gym", "gym workout fitness health"],
      ["🧘", "Yoga", "yoga wellness meditation health"],
      ["🏃", "Running", "running fitness health"],
      ["🚴", "Cycling", "cycling fitness health"],
      ["🏊", "Swimming", "swimming fitness health"],
      ["🥗", "Nutrition", "nutrition healthy food"],
      ["😴", "Sleep", "sleep wellness health"],
    ],
  },
  {
    category: "Education",
    items: [
      ["🎓", "Tuition", "education school university tuition"],
      ["📚", "Books", "books study education reading"],
      ["📖", "Reading", "book reading study"],
      ["✏️", "Stationery", "stationery pencil school office"],
      ["🖊️", "Pens", "pen stationery office"],
      ["📓", "Notebook", "notebook stationery school"],
      ["🎒", "School bag", "school bag education"],
      ["🧑‍🏫", "Teacher", "teacher course class"],
      ["🏫", "School", "school education fees"],
      ["🧪", "Science", "science lab class"],
      ["🔬", "Microscope", "science lab education"],
      ["🎨", "Art class", "art class education"],
      ["🧑‍💻", "Coding", "coding bootcamp technology"],
      ["📜", "Certificate", "certificate course education"],
    ],
  },
  {
    category: "Tech",
    items: [
      ["💻", "Laptop", "laptop computer tech work"],
      ["🖥️", "Desktop", "desktop computer tech"],
      ["⌨️", "Keyboard", "keyboard tech computer"],
      ["🖱️", "Mouse", "mouse computer tech"],
      ["📱", "Phone", "phone mobile tech bill"],
      ["📲", "Mobile plan", "mobile phone plan bill"],
      ["🎧", "Headphones", "headphones audio tech music"],
      ["🎙️", "Microphone", "microphone audio tech"],
      ["📷", "Camera", "camera photography tech"],
      ["🎮", "Console", "games gaming entertainment tech"],
      ["🕹️", "Arcade", "gaming arcade"],
      ["⌚", "Smartwatch", "watch wearable tech"],
      ["🔋", "Battery", "battery charger tech"],
      ["🔌", "Cable", "cable charger power"],
      ["💾", "Storage", "disk storage tech"],
      ["🖨️", "Printer", "printer office tech"],
      ["📡", "Network", "router network tech"],
      ["🤖", "Automation", "robot ai automation tech"],
    ],
  },
  {
    category: "Shopping",
    items: [
      ["👕", "Clothes", "clothes shirt fashion shopping"],
      ["👖", "Pants", "pants jeans clothes fashion"],
      ["👗", "Dress", "dress fashion clothes"],
      ["🧥", "Coat", "coat jacket fashion clothes"],
      ["👟", "Shoes", "shoes sneakers fashion shopping"],
      ["🥾", "Boots", "boots shoes fashion"],
      ["👜", "Bag", "bag purse fashion shopping"],
      ["🎒", "Backpack", "backpack bag shopping"],
      ["💄", "Makeup", "makeup beauty cosmetics"],
      ["💍", "Jewelry", "jewelry ring accessories"],
      ["⌚", "Watch", "watch accessories"],
      ["🛍️", "Shopping bags", "shopping bags retail"],
      ["🏷️", "Sale", "tag discount sale shopping"],
      ["🎁", "Gift", "gift present birthday"],
      ["🧸", "Toys", "toys gifts kids"],
      ["🍼", "Baby", "baby kids child"],
      ["🪑", "Chair", "chair furniture"],
      ["🖼️", "Decor", "decor art frame home"],
    ],
  },
  {
    category: "Entertainment",
    items: [
      ["🎬", "Movies", "movies cinema entertainment"],
      ["🎟️", "Tickets", "tickets event concert cinema"],
      ["🎵", "Music", "music streaming entertainment"],
      ["🎤", "Karaoke", "karaoke singing music"],
      ["🎧", "Audio", "audio headphones music"],
      ["🎮", "Games", "games gaming entertainment"],
      ["🕹️", "Arcade", "arcade gaming entertainment"],
      ["🎲", "Board games", "games board entertainment"],
      ["♟️", "Chess", "chess games hobby"],
      ["🎳", "Bowling", "bowling entertainment"],
      ["🎨", "Art", "art hobby creative"],
      ["📸", "Photography", "photography camera hobby"],
      ["🎭", "Theater", "theater drama entertainment"],
      ["🎪", "Circus", "circus event entertainment"],
      ["🏟️", "Stadium", "sports stadium event"],
      ["⚽", "Football", "football soccer sports"],
      ["🏏", "Cricket", "cricket sports"],
      ["🏀", "Basketball", "basketball sports"],
      ["🎾", "Tennis", "tennis sports"],
      ["🏆", "Trophy", "competition sports"],
    ],
  },
  {
    category: "People",
    items: [
      ["❤️", "Family", "family personal love"],
      ["👨‍👩‍👧", "Family", "family kids home"],
      ["👶", "Baby", "baby child kids"],
      ["🧒", "Child", "child kids school"],
      ["🧑", "Personal", "personal self"],
      ["🧑‍🍳", "Cook", "cook chef food"],
      ["🧑‍⚕️", "Care", "doctor care health"],
      ["🧑‍🔧", "Mechanic", "mechanic repair service"],
      ["🧑‍🎨", "Creative", "artist creative hobby"],
      ["🧑‍💻", "Developer", "developer coding work"],
      ["👥", "Friends", "friends group social"],
      ["🎂", "Birthday", "birthday party gifts"],
      ["🎉", "Party", "party celebration social"],
      ["🙏", "Donation", "donation charity giving"],
      ["🤝", "Support", "support help donation"],
    ],
  },
  {
    category: "Misc",
    items: [
      ["📁", "Folder", "folder files category"],
      ["📌", "Pinned", "pin important"],
      ["📍", "Location", "location place"],
      ["📅", "Calendar", "calendar date monthly"],
      ["⏰", "Reminder", "clock reminder time"],
      ["📝", "Notes", "notes memo writing"],
      ["✅", "Done", "done complete check"],
      ["⚠️", "Warning", "warning alert"],
      ["🔔", "Alert", "notification alert"],
      ["🔁", "Recurring", "repeat recurring subscription"],
      ["♻️", "Recycle", "recycle reusable"],
      ["🌙", "Night", "night evening"],
      ["☀️", "Day", "sun day"],
      ["🌧️", "Rain", "rain weather"],
      ["🐾", "Pets", "pets animal cat dog"],
      ["🐶", "Dog", "dog pet"],
      ["🐱", "Cat", "cat pet"],
      ["🪪", "ID", "id card license document"],
      ["🧿", "Other", "other miscellaneous"],
      ["✨", "Special", "special sparkle"],
    ],
  },
];

export const EMOJI_CATEGORIES = ["All", ...EMOJI_GROUPS.map((group) => group.category)];

export const EMOJI_OPTIONS: EmojiOption[] = EMOJI_GROUPS.flatMap((group) =>
  group.items.map(([emoji, label, keywords]) => ({
    emoji,
    label,
    category: group.category,
    keywords: `${label.toLowerCase()} ${group.category.toLowerCase()} ${keywords}`,
  }))
);
